Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
service = QiskitRuntimeService(channel='ibm_quantum')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAccountNotFoundError[0m                      Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m service [38;5;241m=[39m [43mQiskitRuntimeService[49m[43m([49m[43mchannel[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mibm_quantum[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/qiskit_ibm_runtime/qiskit_runtime_service.py:173[0m, in [0;36mQiskitRuntimeService.__init__[0;34m(self, channel, token, url, filename, name, instance, proxies, verify)[0m
[1;32m    132[0m [38;5;250m[39m[38;5;124;03m"""QiskitRuntimeService constructor[39;00m
[1;32m    133[0m 
[1;32m    134[0m [38;5;124;03mAn account is selected in the following order:[39;00m
[0;32m   (...)[0m
[1;32m    169[0m [38;5;124;03m    IBMInputValueError: If an input is invalid.[39;00m
[1;32m    170[0m [38;5;124;03m"""[39;00m
[1;32m    171[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m()
[0;32m--> 173[0m [38;5;28mself[39m[38;5;241m.[39m_account [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_discover_account[49m[43m([49m
[1;32m    174[0m [43m    [49m[43mtoken[49m[38;5;241;43m=[39;49m[43mtoken[49m[43m,[49m
[1;32m    175[0m [43m    [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m
[1;32m    176[0m [43m    [49m[43minstance[49m[38;5;241;43m=[39;49m[43minstance[49m[43m,[49m
[1;32m    177[0m [43m    [49m[43mchannel[49m[38;5;241;43m=[39;49m[43mchannel[49m[43m,[49m
[1;32m    178[0m [43m    [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mfilename[49m[43m,[49m
[1;32m    179[0m [43m    [49m[43mname[49m[38;5;241;43m=[39;49m[43mname[49m[43m,[49m
[1;32m    180[0m [43m    [49m[43mproxies[49m[38;5;241;43m=[39;49m[43mProxyConfiguration[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mproxies[49m[43m)[49m[43m [49m[38;5;28;43;01mif[39;49;00m[43m [49m[43mproxies[49m[43m [49m[38;5;28;43;01melse[39;49;00m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m,[49m
[1;32m    181[0m [43m    [49m[43mverify[49m[38;5;241;43m=[39;49m[43mverify[49m[43m,[49m
[1;32m    182[0m [43m[49m[43m)[49m
[1;32m    184[0m [38;5;28mself[39m[38;5;241m.[39m_client_params [38;5;241m=[39m ClientParameters(
[1;32m    185[0m     channel[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_account[38;5;241m.[39mchannel,
[1;32m    186[0m     token[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_account[38;5;241m.[39mtoken,
[0;32m   (...)[0m
[1;32m    190[0m     verify[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_account[38;5;241m.[39mverify,
[1;32m    191[0m )
[1;32m    193[0m [38;5;28mself[39m[38;5;241m.[39m_channel [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_account[38;5;241m.[39mchannel

File [0;32m/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/qiskit_ibm_runtime/qiskit_runtime_service.py:269[0m, in [0;36mQiskitRuntimeService._discover_account[0;34m(self, token, url, instance, channel, auth, filename, name, proxies, verify)[0m
[1;32m    267[0m         [38;5;28;01mif[39;00m url:
[1;32m    268[0m             logger[38;5;241m.[39mwarning([38;5;124m"[39m[38;5;124mLoading default [39m[38;5;132;01m%s[39;00m[38;5;124m account. Input [39m[38;5;124m'[39m[38;5;124murl[39m[38;5;124m'[39m[38;5;124m is ignored.[39m[38;5;124m"[39m, channel)
[0;32m--> 269[0m         account [38;5;241m=[39m [43mAccountManager[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[43mfilename[49m[38;5;241;43m=[39;49m[43mfilename[49m[43m,[49m[43m [49m[43mname[49m[38;5;241;43m=[39;49m[43mname[49m[43m,[49m[43m [49m[43mchannel[49m[38;5;241;43m=[39;49m[43mchannel[49m[43m)[49m
[1;32m    270[0m [38;5;28;01melif[39;00m [38;5;28many[39m([token, url]):
[1;32m    271[0m     [38;5;66;03m# Let's not infer based on these attributes as they may change in the future.[39;00m
[1;32m    272[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    273[0m         [38;5;124m"[39m[38;5;124m'[39m[38;5;124mchannel[39m[38;5;124m'[39m[38;5;124m or [39m[38;5;124m'[39m[38;5;124mauth[39m[38;5;124m'[39m[38;5;124m is required if [39m[38;5;124m'[39m[38;5;124mtoken[39m[38;5;124m'[39m[38;5;124m, or [39m[38;5;124m'[39m[38;5;124murl[39m[38;5;124m'[39m[38;5;124m is specified but [39m[38;5;124m'[39m[38;5;124mname[39m[38;5;124m'[39m[38;5;124m is not.[39m[38;5;124m"[39m
[1;32m    274[0m     )

File [0;32m/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/qiskit_ibm_runtime/accounts/management.py:171[0m, in [0;36mAccountManager.get[0;34m(cls, filename, name, channel)[0m
[1;32m    169[0m         [38;5;28;01mif[39;00m os[38;5;241m.[39mpath[38;5;241m.[39misfile(_QISKITRC_CONFIG_FILE):
[1;32m    170[0m             [38;5;28;01mreturn[39;00m [38;5;28mcls[39m[38;5;241m.[39m_from_qiskitrc_file()
[0;32m--> 171[0m         [38;5;28;01mraise[39;00m AccountNotFoundError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo default [39m[38;5;132;01m{[39;00mchannel[38;5;132;01m}[39;00m[38;5;124m account saved.[39m[38;5;124m"[39m)
[1;32m    172[0m     [38;5;28;01mreturn[39;00m Account[38;5;241m.[39mfrom_saved_format(saved_account)
[1;32m    174[0m all_config [38;5;241m=[39m read_config(filename[38;5;241m=[39mfilename)

[0;31mAccountNotFoundError[0m: 'No default ibm_quantum account saved.'

